# Generated by Django 2.1.7 on 2019-03-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Images',
            new_name='Product_Image',
        ),
    ]
