# Generated by Django 2.1.7 on 2019-03-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bill_order_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Method_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Method_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='table',
        ),
        migrations.AddField(
            model_name='order_method_table',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Bill'),
        ),
        migrations.AddField(
            model_name='order_method_table',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Table'),
        ),
        migrations.AddField(
            model_name='order_method_address',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Bill'),
        ),
    ]
