# Generated by Django 2.1.7 on 2019-03-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190324_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_method_address',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order_method_table',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order_method_table',
            name='table',
        ),
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Table'),
        ),
        migrations.DeleteModel(
            name='Order_Method_Address',
        ),
        migrations.DeleteModel(
            name='Order_Method_Table',
        ),
    ]
