# Generated by Django 2.2 on 2019-04-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bill_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='checked_out',
            new_name='finished',
        ),
    ]
